# Generated by Django 4.2.4 on 2023-08-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0001_initial'),
        ('todo', '0002_alter_reminder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='seats.staffseat'),
        ),
    ]
