#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

postgres_ready() {
	python3 <<END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${SQL_DATABASE}",
        user="${SQL_USER}",
        password="${SQL_PASSWORD}",
        host="${SQL_HOST}",
        port="${SQL_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
	echo >&2 'Waiting for PostgreSQL to become available...'
    echo >&2 "dbname=${SQL_DATABASE}"
    echo >&2 "user=${SQL_USER}"
    echo >&2 "password=${SQL_PASSWORD}"
    echo >&2 "host=${SQL_HOST}"
    echo >&2 "port=${SQL_PORT}"
    
	sleep 1
done

echo >&2 'PostgreSQL is available'

exec "$@"
