
services:
  django-tenancy-backend:
    build:
      context: .
      dockerfile: ./compose/dev/backend/Dockerfile
    image: django-tenancy-backend
    command: /start
    volumes:
      - .:/opt/django-tenancy
    ports:
      - "8000:8000"
    env_file:
      - ./.env/.dev
    depends_on:
      - django-tenancy-db
      - django-tenancy-redis

  django-tenancy-db:
    image: postgres:14.4
    volumes:
      - django-tenancy_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env/.dev

  django-tenancy-redis:
    image: redis:latest
    ports:
      - "6379:6379"

    
volumes:
  django-tenancy_postgres_data:
