
services:
  django_realms-backend:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: django_realms-backend
    command: /start
    volumes:
      - .:/opt/django_realms
    expose:
      - "8002"
    env_file:
      - ./.env/.prod
    depends_on:
      - django_realms-db
      - django_realms-redis
  
  django_realms-nginx:
    build: ./compose/production/nginx
    ports:
      - "8082:80"
    depends_on:
      - django_realms-backend
    volumes:
      - .:/opt/django_realms
  
  django_realms-db:
    image: postgres:14.4
    volumes:
      - django_realms_postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    env_file:
      - ./.env/.prod

  django_realms-redis:
    image: redis:latest
    expose:
      - "6379"
    
  

volumes:
  django_realms_postgres_data:
