
services:
  django_realms-backend:
    build:
      context: .
      dockerfile: ./compose/dev/backend/Dockerfile
    image: django_realms-backend
    command: /start
    volumes:
      - .:/opt/django_realms
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./.env/.dev
    depends_on:
      - django_realms-db
      - django_realms-redis

  django_realms-frontend:
    build:
      context: .
      dockerfile: ./compose/dev/frontend/Dockerfile
    image: django_realms-frontend
    volumes:
      - .:/opt/django_realms
    env_file:
      - ./.env/.dev-frontend
    ports:
      - "3000:3000"
    depends_on:
      - django_realms-backend

  django_realms-documentation:
    build:
      context: .
      dockerfile: ./compose/dev/documentation/Dockerfile
    image: django_realms-documentation
    volumes:
      - .:/opt/django_realms
    env_file:
      - ./.env/.dev-documentation
    ports:
      - "3001:3000"
      
  django_realms-db:
    image: postgres:14.4
    volumes:
      - django_realms_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env/.dev

  django_realms-redis:
    image: redis:latest
    expose:
      - "6379"
  
  django_realms-nginx:
    build:
      context: .
      dockerfile: ./compose/dev/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_realms-backend
    volumes:
      - .:/opt/django_realms

    
volumes:
  django_realms_postgres_data:
